# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SMainWindow(object):
    def setupUi(self, SMainWindow):
        SMainWindow.setObjectName("SMainWindow")
        SMainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(SMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        SMainWindow.setCentralWidget(self.centralwidget)
        self.titlebar = QtWidgets.QToolBar(SMainWindow)
        self.titlebar.setFloatable(True)
        self.titlebar.setObjectName("titlebar")
        SMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.titlebar)
        self.actionQuit = QtWidgets.QAction(SMainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionToggleMaximized = QtWidgets.QAction(SMainWindow)
        self.actionToggleMaximized.setObjectName("actionToggleMaximized")
        self.titlebar.addAction(self.actionToggleMaximized)
        self.titlebar.addAction(self.actionQuit)

        self.retranslateUi(SMainWindow)
        self.actionQuit.triggered.connect(SMainWindow.close) # type: ignore
        self.actionToggleMaximized.triggered.connect(SMainWindow.toggle_maximized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SMainWindow)

    def retranslateUi(self, SMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SMainWindow.setWindowTitle(_translate("SMainWindow", "MainWindow"))
        self.titlebar.setWindowTitle(_translate("SMainWindow", "Style Window Title Bar"))
        self.actionQuit.setText(_translate("SMainWindow", "Quit"))
        self.actionToggleMaximized.setText(_translate("SMainWindow", "ToggleMaximized"))
